// <auto-generated />
namespace LibraryBooksClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddField_Book_Link : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddField_Book_Link));
        
        string IMigrationMetadata.Id
        {
            get { return "202011032154136_AddField_Book_Link"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
