//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_id { get; set; }
        public string name { get; set; }
        public Nullable<int> year { get; set; }
        public int id_author { get; set; }
        public int id_subject { get; set; }
        public byte[] image { get; set; }
        public string link { get; set; }
        public string tags { get; set; }
        public string description { get; set; }
        public Nullable<int> counter { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
